10: surmark_red # surmark_950410_red
11: surmark_green # surmark_950400_green
12: surmark_white # surmark_46104_white
20: polyform_a0_red
21: polyform_a0_green
22: polyform_a0_black
30: polyform_a2_red
31: polyform_a2_green
32: polyform_a2_black
33: polyform_a2_yellow
40: color_indicator_red
41: color_indicator_green
42: color_indicator_buoy_red
43: color_indicator_buoy_green
50: dock # dock_n, dock_s
51: banner_1
52: banner_2
53: banner_3
60: vessel_black
61: vessel_yellow
70: racquetball_red
71: racquetball_orange
72: racquetball_blue
