session_name: couguv
start_directory: "~/cougars-dev"
options:
  mouse: on
  default-command: bash --rcfile ~/cougars-dev/config/tmuxp/aliases.sh
windows:
  - window_name: main
    layout: tiled
    panes:
      - shell_command:
          - logs
      - shell_command:
          - cmd: build && restart
            enter: false
      - shell_command:
          - cmd: pull-base
            enter: false
