/**:
  coug_gazebo_world_launch:
    ros__parameters:
      world_file: "sonoma_raceway.sdf.xacro"

  sim_launch:
    ros__parameters:
      agents: ["rover1sim", "rover2sim"]

  imu_filter_madgwick:
    ros__parameters:
      declination: 0.227921 # [rad] WMMHR-2025 (38.1615 N, 122.4546 W, 2026-09-16)

/base_station:
  navsat_odom_node:
    ros__parameters:
      use_parameter_origin: true
      origin_latitude: 38.161479 # [deg]
      origin_longitude: -122.454630 # [deg]
      origin_altitude: 6.39 # [m]

/rover1sim:
  sim_launch:
    ros__parameters:
      location: [2.0, -2.5, 1.0] # [x, y, z] [m]
      rotation: [0.0, 0.0, 0.0] # [roll, pitch, yaw] [deg]

/rover2sim:
  sim_launch:
    ros__parameters:
      location: [-1.0, -2.5, 1.0] # [x, y, z] [m]
      rotation: [0.0, 0.0, 0.0] # [roll, pitch, yaw] [deg]
