/**:
  coug_gazebo_world_launch:
    ros__parameters:
      world_file: "byu.sdf.xacro"

  coug_terrain_launch:
    ros__parameters:
      dem_file: "byu_usgs3dep_1m.vrt"

  sim_launch:
    ros__parameters:
      agents: ["rover1gz", "rover2gz", "rover3gz"]

  imu_filter_madgwick:
    ros__parameters:
      declination: 0.186504 # [rad] WMMHR-2025 (40.2515 N, 111.6496 W, 2026-09-18)

mapviz:
  ros__parameters:
    default_capture_radius: 0.1 # [m]
    default_capture_radius_z: 0.1 # [m]
    default_slip_radius: 0.1 # [m]
    default_slip_radius_z: 0.1 # [m]

/base_station:
  navsat_odom_node:
    ros__parameters:
      use_parameter_origin: true
      origin_latitude: 40.2515095 # [deg]
      origin_longitude: -111.6496175 # [deg]
      origin_altitude: 1424.162 # [m]

/rover1gz:
  sim_launch:
    ros__parameters:
      location: [79.0, -571.0, -4.6] # [x, y, z] [m]
      rotation: [0.0, 0.0, 180.0] # [roll, pitch, yaw] [deg]

  global_costmap:
    global_costmap:
      ros__parameters:
        publish_frequency: 0.5 # [Hz]
        always_send_full_costmap: true

  local_costmap:
    local_costmap:
      ros__parameters:
        publish_frequency: 5.0 # [Hz]
        always_send_full_costmap: true

/rover2gz:
  sim_launch:
    ros__parameters:
      location: [79.0, -568.0, -4.4] # [x, y, z] [m]
      rotation: [0.0, 0.0, 180.0] # [roll, pitch, yaw] [deg]

  global_costmap:
    global_costmap:
      ros__parameters:
        publish_frequency: 0.5 # [Hz]
        always_send_full_costmap: true

  local_costmap:
    local_costmap:
      ros__parameters:
        publish_frequency: 5.0 # [Hz]
        always_send_full_costmap: true

/rover3gz:
  sim_launch:
    ros__parameters:
      location: [79.0, -565.0, -4.3] # [x, y, z] [m]
      rotation: [0.0, 0.0, 180.0] # [roll, pitch, yaw] [deg]

  global_costmap:
    global_costmap:
      ros__parameters:
        publish_frequency: 0.5 # [Hz]
        always_send_full_costmap: true

  local_costmap:
    local_costmap:
      ros__parameters:
        publish_frequency: 5.0 # [Hz]
        always_send_full_costmap: true
