/**:
  coug_gazebo_world_launch:
    ros__parameters:
      world_file: "mdrs.sdf.xacro"

  sim_launch:
    ros__parameters:
      agents: ["rover1sim"]
      dem_file: "mdrs_usgs3dep_1m_ut_southern_ql1_2018.tif"

  imu_filter_madgwick:
    ros__parameters:
      declination: 0.176188 # [rad] WMMHR-2025 (38.4060 N, 110.7920 W, 2026-09-18)

/base_station:
  navsat_odom_node:
    ros__parameters:
      use_parameter_origin: true
      origin_latitude: 38.406 # [deg]
      origin_longitude: -110.792 # [deg]
      origin_altitude: 1373.134 # [m]

/rover1sim:
  sim_launch:
    ros__parameters:
      location: [-12.0, -14.0, -0.4] # [x, y, z] [m]
      rotation: [0.0, 0.0, 0.0] # [roll, pitch, yaw] [deg]
