# Copyright (c) 2026 BYU FROST Lab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  gtsam:
    image: frostlab/cougars:gtsam-${VERSION:-latest}
    build:
      context: .
      dockerfile: .docker/Dockerfile.gtsam
    profiles: ["build-reqs"]

  base:
    image: frostlab/cougars:base-${VERSION:-latest}
    build:
      context: .
      dockerfile: .docker/Dockerfile.base
      args:
        - VERSION=${VERSION:-latest}
    profiles: ["build-reqs"]

  router:
    image: frostlab/cougars:base-${VERSION:-latest}
    container_name: router-ct
    network_mode: host
    ipc: host
    pid: host
    environment:
      - ZENOH_CONFIG_OVERRIDE=connect/endpoints=["tcp/${ZENOH_ROUTER_IP}:7447"]
    restart: unless-stopped
    command: ros2 run rmw_zenoh_cpp rmw_zenohd

  runtime:
    image: frostlab/cougars:runtime-${VERSION:-latest}
    build:
      context: .
      dockerfile: .docker/Dockerfile.runtime
      args:
        - VERSION=${VERSION:-latest}
    container_name: runtime-ct
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    depends_on:
      - router
    environment:
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ROS_DOMAIN_ID=24
    volumes:
      - ./bags:/bags
      - /etc/localtime:/etc/localtime:ro
      - /run/udev:/run/udev:ro
      - /dev:/dev
    restart: unless-stopped
    command: >
      ros2 launch coug_bringup auv.launch.py
      auv_ns:=${AUV_NS}
      use_sim_time:=${USE_SIM_TIME:-false}
