[mypy]
disallow_subclassing_any = False
disallow_untyped_calls = False
ignore_missing_imports = True
implicit_reexport = True
namespace_packages = False
scripts_are_modules = True
strict = True
warn_unused_ignores = False
