/**:
  ros__parameters:
    config_command_topic: "dvl/config/command"
    battery_status_topic: "battery/status"

    bag_record_service: "bag_record"
    arm_thruster_service: "thruster/arm"
    emergency_stop_service: "base/emergency_stop"
    emergency_surface_service: "base/emergency_surface"
    depth_calibrate_service: "depth/calibrate"
    fins_calibrate_service: "fins/calibrate"
