mapviz:
  ros__parameters:
    # --- ROS Topics ---
    waypoint_topic: "waypoints"
    waypoints_map_topic: "waypoints_map"

initialize_origin:
  ros__parameters:
    local_xy_origin: "auto"
    local_xy_origins: [40.33940, -111.90721, 0.0, 0.0]  # [lat, lon, alt, heading]
