/**:
  coug_terrain_launch:
    ros__parameters:
      dem_file: ""

  dem_global_costmap_node:
    ros__parameters:
      # --- Node Settings ---
      max_slope_degrees: 25.0
      resolution: 1.0 # [m]
      outside_is_lethal: false

      # --- ROS Topics and Frames ---
      origin_topic: "/origin"
      output_topic: "terrain/occupancy"

  ground_segmentation_node:
    ros__parameters:
      maxX: 100.0 # [m]
      minX: -100.0 # [m]
      maxY: 100.0 # [m]
      minY: -100.0 # [m]
      maxZ: 100.0 # [m]
      minZ: -100.0 # [m]
      downsample: true
      downsample_resolution: 0.1 # [m]
      lidar_to_ground: -0.875 # [m] Camera to ground along base frame Z.
      transform_tolerance: 0.1 # [s]

      cellSizeX: 1.0 # [m]
      cellSizeY: 1.0 # [m]
      cellSizeZ: 10.0 # [m] Phase 1 vertical binning.
      cellSizeZPhase2: 1.0 # [m] Phase 2 vertical binning.
      slopeThresholdDegrees: 20.0 # [deg]
      groundInlierThreshold: 0.2 # [m] Must stay below cellSizeZPhase2.
      centroidSearchRadius: 5.0 # [m]
      maxGroundHeightDeviation: 0.1 # [m]
      use_imu_orientation: true

      show_benchmark: false
