/**:
  visual_dvl_node:
    ros__parameters:
      # --- Node Settings ---
      sync_slop_sec: 0.05 # [s]

      velocity_noise_sigmas: [0.5, 0.5, 2.0] # [x, y, z] [m/s]

      # --- ROS Topics and Frames ---
      front_image_topic: "stereo/front/image_raw"
      back_image_topic: "stereo/back/image_raw"
      front_camera_info_topic: "stereo/front/camera_info"
      back_camera_info_topic: "stereo/back/camera_info"
      velocity_topic: "dvl/visual"
