mapviz:
  ros__parameters:
    waypoint_topic: "waypoints"
    waypoints_map_topic: "waypoints_map"

    start_service: "base/start"
    stop_service: "base/stop"
    surface_service: "base/surface"
    home_service: "base/home"

initialize_origin:
  ros__parameters:
    local_xy_origin: "auto"
    local_xy_origins: [40.33940, -111.90721, 0.0, 0.0]  # [lat, lon, alt, heading]
