mapviz:
  ros__parameters:
    # --- Waypoint Defaults ---
    default_speed_rpm: 1500.0 # [RPM]
    default_capture_radius: 25.0 # [m]
    default_capture_radius_z: 2.0 # [m]
    default_slip_radius: 50.0 # [m] (typically 2x default_capture_radius)
    default_slip_radius_z: 4.0 # [m]

    default_search_points: 6 # Search points per ring.
    default_search_rings: 2 # Rings of search points.
    default_search_view_width: 4.0 # [m] Width the camera can see; sets the ring spacing.

    # --- ROS Topics and Services ---
    waypoints_topic: "waypoints"
    waypoints_viz_topic: "waypoints_viz"

    start_service: "base/start"
    stop_service: "base/stop"
    surface_service: "base/surface"
    home_service: "base/home"

initialize_origin:
  ros__parameters:
    local_xy_origin: "auto"
