/aquaslam:
  coug_description_launch:
    ros__parameters:
      urdf_file: "aquaslam.urdf.xacro"

  "**":
    ros__parameters:
      base:
        parameter_tf:
          position: [0.132345, 0.032086, -0.240100]
          orientation: [0.999758, 0.001275, -0.014628, 0.016379]

      imu:
        parameter_tf:
          position: [-0.079222, 0.086400, -0.141493]
          orientation: [-0.002529, 0.714814, 0.699222, -0.011101]
        use_parameter_covariance: true
        parameter_covariance:
          accel_noise_sigmas: [0.000196, 0.000196, 0.000196]
          gyro_noise_sigmas: [0.0000873, 0.0000873, 0.0000873]
        accel_bias_rw_sigmas: [0.000392, 0.000392, 0.000392]
        gyro_bias_rw_sigmas: [0.0000388, 0.0000388, 0.0000388]
        gravity: [0.0, 0.0, -9.81]

      gps:
        enable_gps: false

      depth:
        parameter_tf:
          position: [-0.079222, 0.086400, -0.141493]
          orientation: [1.0, 0.0, 0.0, 0.0]
        use_parameter_covariance: true
        parameter_covariance:
          position_z_noise_sigma: 0.005

      mag:
        enable_mag: false

      ahrs:
        enable_ahrs: false
        parameter_tf:
          position: [-0.079222, 0.086400, -0.141493]
          orientation: [-0.002529, 0.714814, 0.699222, -0.011101]
        use_parameter_covariance: true
        parameter_covariance:
          orientation_noise_sigmas: [0.00349, 0.00349, 0.01745]

      dvl:
        parameter_tf:
          position: [0.0, 0.0, 0.0]
          orientation: [0.0, 0.0, 0.0, 1.0]

      prior:
        use_parameter_priors: false

  dvl_a50_twist_node:
    ros__parameters:
      use_fom_covariance: true
      fom_covariance_scale: 4.0

  ekf_filter_node_map:
    ros__parameters:
      imu0: "imu/data_null"

  ukf_filter_node_map:
    ros__parameters:
      imu0: "imu/data_null"
