/bluerov2:
  coug_description_launch:
    ros__parameters:
      urdf_file: "bluerov2.urdf.xacro"

  "**":
    ros__parameters:
      imu:
        use_parameter_covariance: true

      gps:
        enable_gps: false
        enable_gps_init_priors: false

      depth:
        use_parameter_covariance: true

      mag:
        # enable_mag: false
        use_parameter_covariance: true

      # ahrs:
        # enable_ahrs: true

      dvl:
        robust_kernel: "Huber"

      priors:
        use_parameter_priors: false
        use_parameter_priors_covariance: false

  fluid_pressure_odom_node:
    ros__parameters:
      atmospheric_pressure: 86039.8 # Utah Lake (~1358 m elevation)
      max_pressure_delta: 9780.0 # [Pa] ~1 m depth jump

  navsat_odom_node:
    ros__parameters:
      position_covariance_threshold: 0.001 # IMPORTANT! Using RTK GPS ground truth

      use_parameter_origin: false
      use_parameter_child_frame: true

  ekf_filter_node_map:
    ros__parameters:
      odom2: "gps/odometry_null"

  ukf_filter_node_map:
    ros__parameters:
      odom2: "gps/odometry_null"

/base_station:
  navsat_odom_node:
    ros__parameters:
      use_parameter_origin: false
