/blue1holo:
  coug_comms_base_launch:
    ros__parameters:
      beacon_id: 4

  coug_description_launch:
    ros__parameters:
      urdf_file: "bluerov2_holoocean.urdf.xacro"

  coug_helm_launch:
    ros__parameters:
      tree_file: "behaviors_nav2.xml"

  "**":
    ros__parameters:
      publish_velocity_cov: true
      publish_imu_bias_cov: true

      gps:
        enable_gps: false
        enable_gps_init_priors: false

      mag:
        enable_mag: false

      ahrs:
        enable_ahrs: true

      # priors:
      #   parameter_priors:
      #     initial_position: [0.0, 0.0, -275.0] # [x, y, z] [m]

  modem_converter_node:
    ros__parameters:
      beacon_id: 4
