/blue1sim:
  coug_description_launch:
    ros__parameters:
      urdf_file: "bluerov2_holoocean.urdf.xacro"

  "**":
    ros__parameters:
      publish_velocity_cov: true
      publish_imu_bias_cov: true

      gps:
        enable_gps: false

      prior:
        parameter_priors:
          initial_position_sigmas: [0.001, 0.001, 1.0] # [x, y, z] [m]

  behavior_server:
    ros__parameters:
      local_frame: "blue1sim/odom"
      robot_base_frame: "blue1sim/base_link"

  global_costmap:
    global_costmap:
      ros__parameters:
        global_frame: "map"
        robot_base_frame: "blue1sim/base_link"

  local_costmap:
    local_costmap:
      ros__parameters:
        global_frame: "blue1sim/odom"
        robot_base_frame: "blue1sim/base_link"
