/coug1sim:
  coug_comms_base_launch:
    ros__parameters:
      beacon_id: 1

  bt_helm_node:
    ros__parameters:
      publish_groot2: true

  modem_converter_node:
    ros__parameters:
      beacon_id: 1
