/coug2sim:
  "**":
    ros__parameters:
      prior:
        parameter_priors:
          initial_position: [0.0, 20.0, 0.0]

  ekf_filter_node_map:
    ros__parameters:
      initial_state: [0.0, 20.0, 0.0,
                      0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0]

  ukf_filter_node_map:
    ros__parameters:
      initial_state: [0.0, 20.0, 0.0,
                      0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0]

  bt_helm_node:
    ros__parameters:
      publish_groot2: true
      groot2_port: 1669

  coug_comms_base_launch:
    ros__parameters:
      beacon_id: 2

  modem_converter_node:
    ros__parameters:
      beacon_id: 2
