/coug2_ekf/dvl_a50_twist_node:
  ros__parameters:
    use_parameter_frame: true

/coug2_ekf/dvl_a50_odom_node:
  ros__parameters:
    use_parameter_frame: true

/coug2_ekf/fluid_pressure_odom_node:
  ros__parameters:
    atmospheric_pressure: 82776.2 # Deer Creek Reservoir (~1673 m elevation)
    water_density: 997.0
    gravity: 9.81

    max_pressure_delta: 9780.0 # [Pa] ~1 m depth jump

    use_parameter_child_frame: true

/coug2_ekf/navsat_odom_node:
  ros__parameters:
    use_parameter_origin: false
    use_parameter_child_frame: true

/coug2_ekf/seatrac_x150_imu_node:
  ros__parameters:
    orientation_noise_sigmas: [0.00349, 0.00349, 0.01745]
    # https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml#declination
    mag_declination_radians: 0.188 # 10.77 degrees

    use_parameter_frame: true

/coug2_ekf/ekf_filter_node_odom:
  ros__parameters:
    publish_tf: true

    imu0: seatrac/imu/data
    imu0_config: [false, false, false, # X, Y, Z
                  true,  true,  true, # Roll, Pitch, Yaw
                  false, false, false, # Vx, Vy, Vz
                  false, false, false,  # Vroll, Vpitch, Vyaw
                  true,  true,  true]  # Ax, Ay, Az
    imu0_differential: false
    imu0_relative: true

/coug2_ekf/ekf_filter_node_map:
  ros__parameters:
    publish_tf: true

    # odom2: odometry/gps_null
    imu0: seatrac/imu/data
