/rover3gz:
  coug_comms_base_launch:
    ros__parameters:
      beacon_id: 3

  coug_description_launch:
    ros__parameters:
      urdf_file: "rover.urdf.xacro"

  coug_gazebo_agent_launch:
    ros__parameters:
      urdf_file: "rover.gazebo.xacro"

  coug_helm_launch:
    ros__parameters:
      tree_file: "follow_waypoints_nav2_w_aruco.xml"

  navsat_odom_node:
    ros__parameters:
      ahrs_topic: "camera/imu/data"

  ekf_filter_node_odom:
    ros__parameters:
      imu0: "camera/imu/data_raw"
      # IMPORTANT! Handle non-trivial IMU rotation for robot_localization gravity mishandling bug.
      imu0_config: [
          false,
          false,
          false, # X, Y, Z
          false,
          false,
          false, # Roll, Pitch, Yaw
          false,
          false,
          false, # Vx, Vy, Vz
          true,
          true,
          true, # Vroll, Vpitch, Vyaw
          false,
          false,
          false, # Ax, Ay, Az
        ]

      odom0: "camera/odom"
      odom0_config: [
          true,
          true,
          true, # X, Y, Z
          true,
          true,
          true, # Roll, Pitch, Yaw
          false,
          false,
          false, # Vx, Vy, Vz
          false,
          false,
          false, # Vroll, Vpitch, Vyaw
          false,
          false,
          false, # Ax, Ay, Az
        ]
      odom0_queue_size: 10
      odom0_differential: false
      odom0_relative: false
      odom0_pose_use_child_frame: true # Handle non-trivial base frame offset.

  ekf_filter_node_map:
    ros__parameters:
      publish_tf: true

      imu0: "camera/imu/data_raw"
      # IMPORTANT! Handle non-trivial IMU rotation for robot_localization gravity mishandling bug.
      imu0_config: [
          false,
          false,
          false, # X, Y, Z
          false,
          false,
          false, # Roll, Pitch, Yaw
          false,
          false,
          false, # Vx, Vy, Vz
          true,
          true,
          true, # Vroll, Vpitch, Vyaw
          false,
          false,
          false, # Ax, Ay, Az
        ]

      imu1: "camera/imu/data"

      odom1_config: [
          true,
          true,
          true, # X, Y, Z
          false,
          false,
          false, # Roll, Pitch, Yaw
          false,
          false,
          false, # Vx, Vy, Vz
          false,
          false,
          false, # Vroll, Vpitch, Vyaw
          false,
          false,
          false, # Ax, Ay, Az
        ]

      odom2: "camera/odom"
      odom2_config: [
          true,
          true,
          true, # X, Y, Z
          false,
          false,
          true, # Roll, Pitch, Yaw
          false,
          false,
          false, # Vx, Vy, Vz
          false,
          false,
          false, # Vroll, Vpitch, Vyaw
          false,
          false,
          false, # Ax, Ay, Az
        ]
      odom2_queue_size: 10
      odom2_differential: true
      odom2_relative: false
      odom2_pose_use_child_frame: true # Handle non-trivial base frame offset.

  controller_server:
    ros__parameters:
      controller_frequency: 20.0 # [Hz]

      general_goal_checker:
        xy_goal_tolerance: 1.45 # [m] 0.9 + 0.55 (base_link to nearest footprint edge)

      FollowPath:
        transform_tolerance: 0.3 # [s]
        time_steps: 56 # [steps]
        model_dt: 0.05 # [s]
        batch_size: 1000

        motion_model: "DiffDrive"
        vx_max: 1.0 # [m/s]
        vx_min: -0.7 # [m/s]
        wz_max: 3.8 # [rad/s]

        vx_std: 0.4 # [m/s]
        wz_std: 0.8 # [rad/s]

        prune_distance: 6.0 # [m]

        critics:
          [
            "ConstraintCritic",
            "CostCritic",
            "GoalCritic",
            "GoalAngleCritic",
            "PathAlignCritic",
            "PathAngleCritic",
            "PathFollowCritic",
            "PreferForwardCritic",
            "TwirlingCritic",
          ]

        CostCritic:
          consider_footprint: true

        GoalCritic:
          threshold_to_consider: 3.0 # [m]

        PathFollowCritic:
          cost_weight: 5.0
          offset_from_furthest: 5 # [poses]
          threshold_to_consider: 3.0 # [m]

        PreferForwardCritic:
          cost_weight: 7.5

  global_costmap:
    global_costmap:
      ros__parameters:
        update_frequency: 1.0 # [Hz]
        publish_frequency: 0.0 # [Hz]

        footprint: "[[0.95, 0.55], [0.95, -0.55], [-0.7, -0.55], [-0.7, 0.55]]"
        plugins:
          ["terrain_layer", "ground_consistency_layer", "inflation_layer"]

        terrain_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          map_topic: "/rover3gz/terrain/occupancy"
          subscribe_to_updates: false
          map_subscribe_transient_local: true

        ground_consistency_layer:
          plugin: "nav2_ground_consistency_costmap_plugin::GroundConsistencyLayer"
          ground_points_topic: "/rover3gz/ground_segmentation/ground_points"
          nonground_points_topic: "/rover3gz/ground_segmentation/obstacle_points"

          robot_height: 1.425 # [m]
          max_data_range: 0.0 # [m]

        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 2.0 # [m]
          cost_scaling_factor: 3.0 # [1/m]

  local_costmap:
    local_costmap:
      ros__parameters:
        update_frequency: 5.0 # [Hz]
        publish_frequency: 1.0 # [Hz]

        footprint: "[[0.95, 0.55], [0.95, -0.55], [-0.7, -0.55], [-0.7, 0.55]]"
        plugins: ["ground_consistency_layer", "inflation_layer"]

        ground_consistency_layer:
          plugin: "nav2_ground_consistency_costmap_plugin::GroundConsistencyLayer"
          ground_points_topic: "/rover3gz/ground_segmentation/ground_points"
          nonground_points_topic: "/rover3gz/ground_segmentation/obstacle_points"

          robot_height: 1.425 # [m]
          # https://github.com/stereolabs/zed-ros2-wrapper/blob/v5.4.1/zed_wrapper/config/zed2i.yaml
          max_data_range: 15.0 # [m]

        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 1.2 # [m]
          cost_scaling_factor: 6.0 # [1/m]

  planner_server:
    ros__parameters:
      GridBased:
        plugin: "nav2_navfn_planner::NavfnPlanner"
