/turtlmap:
  coug_description_launch:
    ros__parameters:
      urdf_file: "turtlmap.urdf.xacro"

  "**":
    ros__parameters:
      imu:
        use_parameter_frame: true
        sensor_rate_hz: 250.0 # [Hz] /nav/filtered_imu/data
        use_parameter_sigmas: true
        parameter_sigmas:
          accel_noise_density_sigmas: [2.4525e-4, 2.4525e-4, 2.4525e-4] # [x, y, z] [m/s^2/√Hz] br2config.yaml
          gyro_noise_density_sigmas: [8.726646e-5, 8.726646e-5, 8.726646e-5] # [x, y, z] [rad/s/√Hz] br2config.yaml
        accel_bias_rw_sigmas: [6.20438876e-3, 6.20438876e-3, 6.20438876e-3] # [x, y, z] [m/s^2/√s] br2config.yaml
        gyro_bias_rw_sigmas: [6.1324618e-4, 6.1324618e-4, 6.1324618e-4] # [x, y, z] [rad/s/√s] br2config.yaml
        integration_covariance: 1.0e-8 # TURTLMap Posegraph.cpp setImuParams()
        gravity: [0.0, 0.0, -9.81007] # [x, y, z] [m/s^2] br2config.yaml (g: 9.81007)

      dvl_topic: "dvl/twist_fom"

      gps:
        enable_gps: false
        enable_gps_init_priors: false

      depth:
        use_parameter_sigmas: true
        parameter_sigmas:
          position_z_noise_sigma: 0.005 # [m] TURTLMap PosegraphBackendOnline.cpp addBarometricFactor()

      mag:
        enable_mag: false

      ahrs:
        use_parameter_frame: true
        enable_ahrs: true
        use_parameter_sigmas: true # TODO: Test this
        parameter_sigmas:
          # https://docs.clearpathrobotics.com/assets/files/clearpath_robotics_014603-TDS1-8efeae7b74bd54c43ea676651f063dbf.pdf
          orientation_noise_sigmas: [0.00436, 0.00436, 0.01396] # [roll, pitch, yaw] [rad]

      priors:
        use_parameter_priors: false
        use_parameter_priors_sigmas: false
        parameter_priors_sigmas:
          initial_velocity_sigmas: [0.1, 0.1, 0.1] # [x, y, z] [m/s] TURTLMap PosegraphBackendOnline.cpp callbackDVL()
        # https://docs.clearpathrobotics.com/assets/files/clearpath_robotics_014603-TDS1-8efeae7b74bd54c43ea676651f063dbf.pdf
        initial_gyro_bias_sigmas: [3.9e-5, 3.9e-5, 3.9e-5] # [x, y, z] [rad/s]

  ekf_filter_node_odom:
    ros__parameters:
      gravitational_acceleration: 9.81007 # [m/s^2] br2config.yaml (g: 9.81007)
      initial_estimate_covariance: [
          1.0e-6,
          1.0e-6,
          1.0e-6, # X, Y, Z
          1.0e-6,
          1.0e-6,
          1.0e-6, # Roll, Pitch, Yaw
          1.0e-2,
          1.0e-2,
          1.0e-2, # Vx, Vy, Vz
          1.0e-9,
          1.0e-9,
          1.0e-9, # Vroll, Vpitch, Vyaw
          1.0e-9,
          1.0e-9,
          1.0e-9, # Ax, Ay, Az
        ]

      # IMPORTANT! Handle non-trivial IMU rotation for robot_localization gravity mishandling bug.
      imu0_config: [
          false,
          false,
          false, # X, Y, Z
          false,
          false,
          false, # Roll, Pitch, Yaw
          false,
          false,
          false, # Vx, Vy, Vz
          true,
          true,
          true, # Vroll, Vpitch, Vyaw
          false,
          false,
          false, # Ax, Ay, Az
        ]

  ekf_filter_node_map:
    ros__parameters:
      gravitational_acceleration: 9.81007 # [m/s^2] br2config.yaml (g: 9.81007)
      initial_estimate_covariance: [
          1.0e-6,
          1.0e-6,
          1.0e-6, # X, Y, Z
          1.0e-6,
          1.0e-6,
          1.0e-6, # Roll, Pitch, Yaw
          1.0e-2,
          1.0e-2,
          1.0e-2, # Vx, Vy, Vz
          1.0e-9,
          1.0e-9,
          1.0e-9, # Vroll, Vpitch, Vyaw
          1.0e-9,
          1.0e-9,
          1.0e-9, # Ax, Ay, Az
        ]

      # IMPORTANT! Handle non-trivial IMU rotation for robot_localization gravity mishandling bug.
      imu0_config: [
          false,
          false,
          false, # X, Y, Z
          false,
          false,
          false, # Roll, Pitch, Yaw
          false,
          false,
          false, # Vx, Vy, Vz
          true,
          true,
          true, # Vroll, Vpitch, Vyaw
          false,
          false,
          false, # Ax, Ay, Az
        ]

  ukf_filter_node_map:
    ros__parameters:
      gravitational_acceleration: 9.81007 # [m/s^2] br2config.yaml (g: 9.81007)
      initial_estimate_covariance: [
          1.0e-6,
          1.0e-6,
          1.0e-6, # X, Y, Z
          1.0e-6,
          1.0e-6,
          1.0e-6, # Roll, Pitch, Yaw
          1.0e-2,
          1.0e-2,
          1.0e-2, # Vx, Vy, Vz
          1.0e-9,
          1.0e-9,
          1.0e-9, # Vroll, Vpitch, Vyaw
          1.0e-9,
          1.0e-9,
          1.0e-9, # Ax, Ay, Az
        ]

      # IMPORTANT! Handle non-trivial IMU rotation for robot_localization gravity mishandling bug.
      imu0_config: [
          false,
          false,
          false, # X, Y, Z
          false,
          false,
          false, # Roll, Pitch, Yaw
          false,
          false,
          false, # Vx, Vy, Vz
          true,
          true,
          true, # Vroll, Vpitch, Vyaw
          false,
          false,
          false, # Ax, Ay, Az
        ]

  fluid_pressure_odom_node:
    ros__parameters:
      pressure_scale: 100.0 # IMPORTANT! Pressure is in hPa, not Pa
      atmospheric_pressure: 99339.996 # [Pa] br2config.yaml (atm_press: 993.39996 hPa)

      use_parameter_child_frame: true

  dvl_a50_twist_beams_node:
    ros__parameters:
      use_parameter_frame: true
      override_timestamp: true # DVL A50 clock is not synced in these bags
