/turtlmap:
  coug_description_launch:
    ros__parameters:
      urdf_file: "turtlmap.urdf.xacro"

  "**":
    ros__parameters:
      imu:
        use_parameter_frame: true
        use_parameter_covariance: true
        parameter_covariance:
          accel_noise_sigmas: [0.00024525, 0.00024525, 0.00024525] # [m/s^2/√Hz] br2config.yaml
          gyro_noise_sigmas: [8.726646e-05, 8.726646e-05, 8.726646e-05] # [rad/s/√Hz] br2config.yaml
        accel_bias_rw_sigmas: [0.00620438876, 0.00620438876, 0.00620438876] # [m/s^2/√s] br2config.yaml
        gyro_bias_rw_sigmas: [0.00061324618, 0.00061324618, 0.00061324618] # [rad/s/√s] br2config.yaml
        integration_covariance: 1.0e-8 # TURTLMap Posegraph.cpp setImuParams()
        gravity: [0.0, 0.0, -9.81007] # [m/s^2] br2config.yaml (g: 9.81007)

      gps:
        enable_gps: false

      depth:
        use_parameter_covariance: true
        parameter_covariance:
          position_z_noise_sigma: 0.005 # [m] TURTLMap PosegraphBackendOnline.cpp addBarometricFactor()

      mag:
        enable_mag: false

      ahrs:
        use_parameter_frame: true
        enable_ahrs: true
        use_parameter_covariance: true
        parameter_covariance:
          # LORD 3DM-GX5-25 EKF attitude: ±0.25° roll/pitch, ±0.8° heading RMS.
          # https://www.microstrain.com/inertial-sensors/3dm-gx5-25
          orientation_noise_sigmas: [0.00436, 0.00436, 0.01396] # [roll, pitch, yaw] [rad]

      priors:
        use_parameter_priors: false
        initial_velocity_sigmas: [0.1, 0.1, 0.1] # [m/s] TURTLMap PosegraphBackendOnline.cpp callbackDVL()

  ekf_filter_node_odom:
    ros__parameters:
      # IMPORTANT! Handle non-trivial IMU rotation for robot_localization gravity mishandling bug.
      imu0_config: [false, false, false, # X, Y, Z
                    false, false, false, # Roll, Pitch, Yaw
                    false, false, false, # Vx, Vy, Vz
                    true,  true,  true,  # Vroll, Vpitch, Vyaw
                    false, false, false] # Ax, Ay, Az

  fluid_pressure_odom_node:
    ros__parameters:
      pressure_scale: 100.0 # IMPORTANT! Pressure is in hPa, not Pa
      atmospheric_pressure: 99339.996 # [Pa] br2config.yaml (atm_press: 993.39996 hPa)

      use_parameter_child_frame: true

  dvl_a50_twist_node:
    ros__parameters:
      use_fom_covariance: true
      fom_covariance_scale: 4.0

      use_parameter_frame: true
      override_timestamp: true # DVL A50 clock is not synced in these bags
