/wamv1sim:
  coug_description_launch:
    ros__parameters:
      urdf_file: "wamv_holoocean.urdf.xacro"

  "**":
    ros__parameters:
      prior:
        parameter_priors:
          initial_position_sigmas: [0.001, 0.001, 1.0] # [x, y, z] [m]

  cmd_vel_converter_node:
    ros__parameters:
      agent_type: "surface_vessel"

  global_costmap:
    global_costmap:
      ros__parameters:
        global_frame: "map"
        robot_base_frame: "wamv1sim/base_link"

  local_costmap:
    local_costmap:
      ros__parameters:
        global_frame: "wamv1sim/odom"
        robot_base_frame: "wamv1sim/base_link"
