/wamv1holo:
  coug_comms_base_launch:
    ros__parameters:
      beacon_id: 5

  coug_description_launch:
    ros__parameters:
      urdf_file: "wamv_holoocean.urdf.xacro"

  coug_helm_launch:
    ros__parameters:
      tree_file: "behaviors_nav2.xml"

  "**":
    ros__parameters:
      priors:
        parameter_priors_sigmas:
          initial_position_sigmas: [0.001, 0.001, 1.0] # [x, y, z] [m]

  cmd_vel_converter_node:
    ros__parameters:
      agent_type: "surface_vessel"

  modem_converter_node:
    ros__parameters:
      beacon_id: 5

  controller_server:
    ros__parameters:
      controller_frequency: 20.0 # [Hz]

      general_goal_checker:
        xy_goal_tolerance: 2.5 # [m]

      FollowPath:
        transform_tolerance: 0.3 # [s]
        time_steps: 56 # [steps]
        model_dt: 0.05 # [s]
        batch_size: 1000

        motion_model: "DiffDrive"
        vx_max: 1.0 # [m/s]
        vx_min: -0.7 # [m/s]
        wz_max: 3.8 # [rad/s]

        vx_std: 0.4 # [m/s]
        wz_std: 0.8 # [rad/s]

        prune_distance: 6.0 # [m]

        critics:
          [
            "ConstraintCritic",
            "CostCritic",
            "GoalCritic",
            "GoalAngleCritic",
            "PathAlignCritic",
            "PathAngleCritic",
            "PathFollowCritic",
            "PreferForwardCritic",
            "TwirlingCritic",
          ]

        CostCritic:
          consider_footprint: true

        GoalCritic:
          threshold_to_consider: 3.0 # [m]

        PathFollowCritic:
          cost_weight: 5.0
          offset_from_furthest: 5 # [poses]
          threshold_to_consider: 3.0 # [m]

        PreferForwardCritic:
          cost_weight: 7.5

  global_costmap:
    global_costmap:
      ros__parameters:
        update_frequency: 1.0 # [Hz]
        publish_frequency: 0.0 # [Hz]

        footprint: "[[2.555, 1.267], [2.555, -1.267], [-2.822, -1.267], [-2.822, 1.267]]"
        plugins: ["obstacle_layer", "inflation_layer"]

        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
          observation_sources: "marking_cloud clearing_cloud"

          marking_cloud:
            topic: "/wamv1holo/camera/point_cloud/cloud_registered"
            data_type: "PointCloud2"
            marking: true
            clearing: false
            min_obstacle_height: 0.5 # [m]
            max_obstacle_height: 2.0 # [m]
            obstacle_max_range: 10.0 # [m]

          clearing_cloud:
            topic: "/wamv1holo/camera/point_cloud/cloud_registered"
            data_type: "PointCloud2"
            marking: false
            clearing: true
            min_obstacle_height: -10.0 # [m]
            max_obstacle_height: 2.0 # [m]
            raytrace_max_range: 15.0 # [m]

        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 2.0 # [m]
          cost_scaling_factor: 3.0 # [1/m]

  local_costmap:
    local_costmap:
      ros__parameters:
        update_frequency: 5.0 # [Hz]
        publish_frequency: 1.0 # [Hz]

        footprint: "[[2.555, 1.267], [2.555, -1.267], [-2.822, -1.267], [-2.822, 1.267]]"
        plugins: ["obstacle_layer", "inflation_layer"]

        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
          observation_sources: "marking_cloud clearing_cloud"

          marking_cloud:
            topic: "/wamv1holo/camera/point_cloud/cloud_registered"
            data_type: "PointCloud2"
            marking: true
            clearing: false
            min_obstacle_height: 0.5 # [m]
            max_obstacle_height: 2.0 # [m]
            # https://github.com/stereolabs/zed-ros2-wrapper/blob/v5.4.1/zed_wrapper/config/zed2i.yaml
            obstacle_max_range: 15.0 # [m]

          clearing_cloud:
            topic: "/wamv1holo/camera/point_cloud/cloud_registered"
            data_type: "PointCloud2"
            marking: false
            clearing: true
            min_obstacle_height: -10.0 # [m]
            max_obstacle_height: 2.0 # [m]
            raytrace_max_range: 15.0 # [m]

        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 3.0 # [m]
          cost_scaling_factor: 2.3 # [1/m]

  planner_server:
    ros__parameters:
      GridBased:
        plugin: "nav2_navfn_planner::NavfnPlanner"
