/**:
  coug_comms_base_launch:
    ros__parameters:
      beacon_id: 1

  base_dispatcher_node:
    ros__parameters:
      # --- Node Settings ---
      publish_diagnostics: false # Publish diagnostic information.
      service_history_size: 5

      direct_timeout_sec: 2.0 # [s] Direct link timeout

      # --- ROS Topics ---
      modem_send_topic: "modem_send"

      start_service: "base/start"
      stop_service: "base/stop"
      surface_service: "base/surface"
      home_service: "base/home"
      emergency_stop_service: "base/emergency_stop"
      emergency_surface_service: "base/emergency_surface"

      direct_status_topic: "status"
      direct_start_service: "start"
      direct_stop_service: "stop"
      direct_surface_service: "surface"
      direct_home_service: "home"
      direct_emergency_stop_service: "emergency_stop"
      direct_emergency_surface_service: "emergency_surface"

  auv_receiver_node:
    ros__parameters:
      # --- Node Settings ---
      publish_diagnostics: false # Publish diagnostic information.
      service_history_size: 5

      # --- ROS Topics ---
      modem_rec_topic: "modem_rec"

      start_service: "start"
      stop_service: "stop"
      surface_service: "surface"
      home_service: "home"
      emergency_stop_service: "emergency_stop"
      emergency_surface_service: "emergency_surface"

  base_status_poller_node:
    ros__parameters:
      # --- Node Settings ---
      publish_diagnostics: false # Publish diagnostic information.
      diagnostic_timeout_sec: 10.0 # [s]

      direct_timeout_sec: 2.0 # [s] Direct link timeout
      tick_period_sec: 0.05 # [s]
      poll_period_sec: 0.0 # [s]
      response_timeout_sec: 5.0 # [s]

      # --- ROS Topics ---
      modem_send_topic: "modem_send"
      modem_rec_topic: "modem_rec"
      modem_cmd_update_topic: "modem_cmd_update"

      status_topic: "base/status"
      direct_status_topic: "status"

  auv_status_stager_node:
    ros__parameters:
      # --- Node Settings ---
      publish_diagnostics: false # Publish diagnostic information.
      diagnostic_timeout_sec: 0.5 # [s]

      # --- ROS Topics ---
      modem_send_topic: "modem_send"
      status_topic: "status"

  base_status_extractor_node:
    ros__parameters:
      # --- ROS Topics ---
      status_topic: "base/status"
      odom_topic: "base/odometry/global"
      depth_topic: "base/odometry/depth"
      imu_topic: "base/imu/data"

  auv_status_bundler_node:
    ros__parameters:
      # --- ROS Topics ---
      status_topic: "status"
      odom_topic: "odometry/global"
      depth_topic: "odometry/depth"
      imu_topic: "imu/data"
