# Copyright 2026 BYU FROST Lab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# --- Cache Stage ---
FROM ubuntu:24.04 AS cacher

WORKDIR /tmp/packages
COPY ros2_ws/src .
RUN find . -type f \! -name "package.xml" -delete

# --- Main Stage ---
FROM frostlab/cougars:gtsam AS runtime

ARG DEBIAN_FRONTEND=noninteractive

SHELL [ "/bin/bash", "-c" ]

ENV DOCKER_USER=root \
  OVERLAY_WS=/ros2_ws \
  CONFIG_DIR=/config \
  BAGS_DIR=/bags \
  RCUTILS_COLORIZED_OUTPUT=1

# Install system dependencies and configure SSH client
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
  apt-get update && apt-get install -y --no-install-recommends \
  openssh-client \
  tmux \
  vim \
  && mkdir -p /etc/ssh/ssh_config.d \
  && printf 'Host github.com\n    StrictHostKeyChecking accept-new\n' > /etc/ssh/ssh_config.d/10-github.conf

# Install ROS packages
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
  apt-get update && apt-get install -y --no-install-recommends \
  "ros-${ROS_DISTRO}-joy" \
  "ros-${ROS_DISTRO}-rmw-cyclonedds-cpp" \
  "ros-${ROS_DISTRO}-rmw-zenoh-cpp" \
  "ros-${ROS_DISTRO}-teleop-tools" \
  "ros-${ROS_DISTRO}-teleop-twist-joy" \
  "ros-${ROS_DISTRO}-teleop-twist-keyboard"

# Install ROS dependencies (rosdep)
RUN --mount=type=bind,from=cacher,source=/tmp/packages,target=/tmp/packages \
  --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
  --mount=type=cache,target=/root/.ros/rosdep \
  apt-get update \
  && rosdep update \
  && rosdep install --from-paths /tmp/packages --ignore-src -y

# Install GeographicLib datasets required by MAVROS
RUN "/opt/ros/${ROS_DISTRO}/lib/mavros/install_geographiclib_datasets.sh"

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc \
  && echo "[ -f ${OVERLAY_WS}/install/setup.bash ] && source ${OVERLAY_WS}/install/setup.bash" >> /root/.bashrc

COPY .docker/entrypoint.sh /entrypoint.sh

WORKDIR ${OVERLAY_WS}

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/bin/bash" ]
