- ros_topic_name: "camera/depth/camera_info"
  gz_topic_name: "camera/depth/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "camera/rgb/image_rect_color"
  gz_topic_name: "camera/depth/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "camera/depth/depth_registered"
  gz_topic_name: "camera/depth/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
