<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>coug_bringup</name>
  <version>0.0.0</version>
  <description>System-wide ROS 2 launch configurations.</description>
  <maintainer email="snelsond@byu.edu">snelsondurrant</maintainer>
  <license>Apache-2.0</license>
  <url type="repository">https://github.com/cougars-auv/cougars-dev</url>

  <exec_depend>coug_active_fgo</exec_depend>
  <exec_depend>coug_comms</exec_depend>
  <exec_depend>coug_description</exec_depend>
  <exec_depend>coug_fg</exec_depend>
  <exec_depend>coug_helm</exec_depend>
  <exec_depend>coug_interfaces</exec_depend>
  <exec_depend>coug_visual_dvl</exec_depend>
  <exec_depend>diagnostic_common_diagnostics</exec_depend>
  <exec_depend>diagnostic_msgs</exec_depend>
  <exec_depend>diagnostic_updater</exec_depend>
  <exec_depend>gps_tools</exec_depend>
  <exec_depend>gpsd_client</exec_depend>
  <exec_depend>mavros</exec_depend>
  <exec_depend>ntrip_client</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sbg_driver</exec_depend>

  <test_depend>python3-pytest</test_depend>
  <test_depend>python3-pytest-cov</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
